version: '3'
services:
  frontend:
    build: 
      context: ./frontend
      args:
        NODE_ENV: production
    ports:
     - "3000:3000"
    depends_on:
     - backend
  backend:
    build: 
      context: ./backend
      args:
        NODE_ENV: production
    ports:
     - "5000:5000"